# Generated by Django 4.1.3 on 2022-11-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychattapp', '0003_friend_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
