# Generated by Django 4.1.3 on 2022-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mychattapp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
