# Generated by Django 4.1.3 on 2022-11-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mychattapp', '0009_friend_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chattmessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('msg_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='mychattapp.profile')),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to='mychattapp.profile')),
            ],
        ),
    ]
